version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gestion_apprenant
      POSTGRES_USER: fadildev
      POSTGRES_PASSWORD: fadildev_44
    ports:
      - "5433:5432"
  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
